---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    notebook_metadata_filter: jupytext_formats
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.3.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# DATA MINING CUP 2018


## Sales forecast for sporting goods


### Djeysi Kathleen Alve, Jônatas Passos, Victor Gabriel.

```{python}
# %autosave 0
```

### Importação das bibliotecas utilizadas

```{python}
import pandas as pd
import numpy as np
import datetime
from sklearn.linear_model import LogisticRegression
import re
from sklearn import preprocessing

regex = r"([0-9]{4}-[0-9]{2})-([0-9]{2})"
```

### Definição das funções utilizadas

```{python}
def evaluation(y_pred, y_real):
    diff = y_pred - y_real
    diff = np.absolute(diff)
    result = np.sqrt(sum(diff))
    return result
```

```{python}
def insert_column (data,fields,fields_name):
    index = len(data.columns)-1
    for i in range(len(fields_name)):
        data.insert(index + i,fields_name[i],fields[fields_name[i]],True)
    return data
```

### Leitura dos arquivos CSV 

```{python}
train = pd.read_csv('train.csv', sep='|')
items = pd.read_csv('items.csv', sep='|')
realclass = pd.read_csv('realclass.csv', sep='|')

items = items.fillna("None")
train = train.fillna("None")
```

### Organizando arquivo de teste (realclass)

```{python}
from datetime import datetime
realclass['target'] = realclass['soldOutDate'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d').day)
```

```{python}
realclass = realclass.drop(['soldOutDate'], axis=1)
```

```{python}
realclass = pd.merge(items, realclass, on=['pid','size'])
```

```{python}
d2 = datetime.strptime('2018-02-01','%Y-%m-%d')
realclass['releaseDate'] = realclass['releaseDate'].apply(lambda x: (d2 -datetime.strptime(x,'%Y-%m-%d')).days)
```

```{python}
realclass
```

```{python}
categories = pd.get_dummies(realclass['category'])
mainCategories = pd.get_dummies(realclass['mainCategory'])
subCategories = pd.get_dummies(realclass['subCategory'])
color = pd.get_dummies(realclass['color'])
brand = pd.get_dummies(realclass['brand'])
```

```{python}
mainCategories.columns = ['mcat-1', 'mcat-9', 'mcat-15']
# realclass = insert_column(realclass, categories, categories.columns)
realclass = insert_column(realclass, mainCategories, mainCategories.columns)
# realclass = insert_column(realclass, subCategories, subCategories.columns)
# realclass = insert_column(realclass, color, color.columns)
# realclass = insert_column(realclass, brand, brand.columns)
```

```{python}
realclass = realclass.drop(['category'], axis=1)
realclass = realclass.drop(['mainCategory'], axis=1)
realclass = realclass.drop(['subCategory'], axis=1)
realclass = realclass.drop(['color'], axis=1)
#data = data.drop(['pid'], axis=1)
realclass = realclass.drop(['brand'], axis=1)
#data = data.drop(['size'], axis=1)
#data = data.drop(['releaseDate'], axis=1)
realclass = realclass.drop(['mcat-1'], axis=1)
```

### Criando variavel mês

```{python}
month = []
for i in train["date"]:
    month.append(re.search(regex, i).group(1))
```

```{python}
train.insert(1,"month",month)
```

```{python}
from copy import deepcopy
new_data = deepcopy(items)
```

### Realizando estudo da variavel units

```{python}
units = train.sort_values(by=['units'])['units'].reset_index()['units']
```

```{python}
units[units.index > 134000]
```

```{python}
import matplotlib.pyplot as plt 
plt.plot(units) 
   
plt.title('Units graph!') 
  
plt.show() 
```

```{python}
train = train[train['units'] < 20]
```

```{python}
len(train['units'])
```

### Criando variavel com o total de vendas

```{python}
total_solds = train.groupby(['pid','size']).sum()
```

```{python}
realclass = pd.merge(total_solds, realclass, on=['pid','size'])
```

### Alterando granularidade para "pid", "size" e "month"

```{python}
x = train.groupby(['pid','size','month']).tail(1).sort_values(by=['pid']).drop(['units'], axis=1)
```

```{python}
grouped = train.groupby(['pid','size','month']).sum()
```

```{python}
grouped.index = x.index
```

```{python}
x = x.sort_values(by=['pid','month'])
```

```{python}
data = pd.merge(items.drop(['stock'], axis=1), x, on=['pid','size'])
```

```{python}
data['units'] = grouped['units'].values
```

### Realizando dummies das variaveis categoricas

```{python}
categories = pd.get_dummies(data['category'])
mainCategories = pd.get_dummies(data['mainCategory'])
subCategories = pd.get_dummies(data['subCategory'])
color = pd.get_dummies(data['color'])
brand = pd.get_dummies(data['brand'])
```

```{python}
# categories.columns = ['cat-2', 'cat-7', 'cat-10', 'cat-16', 'cat-18', 'cat-24', 'cat-30', 'cat-33', 'cat-36', 'cat-37']

mainCategories.columns = ['mcat-1', 'mcat-9', 'mcat-15']

# subCategories.columns = [ 'subcat-3.0',    'subcat-4.0',    'subcat-5.0',    'subcat-6.0',    'subcat-8.0',   'subcat-11.0',   'subcat-12.0',   'subcat-13.0',   'subcat-14.0',
#          'subcat-16.0',   'subcat-17.0',   'subcat-19.0',   'subcat-20.0',   'subcat-21.0',   'subcat-22.0',   'subcat-23.0',   'subcat-25.0',   'subcat-26.0',
#          'subcat-27.0',   'subcat-28.0',   'subcat-29.0',   'subcat-31.0',   'subcat-32.0',   'subcat-34.0',   'subcat-35.0',   'subcat-38.0',   'subcat-39.0',
#          'subcat-40.0',   'subcat-41.0',   'subcat-42.0',   'subcat-43.0',   'subcat-44.0', 'subcat-None']
```

```{python}
# data = insert_column(data,categories, categories.columns)
data = insert_column(data,mainCategories, mainCategories.columns)
# data = insert_column(data,subCategories, subCategories.columns)
# data = insert_column(data, color, color.columns)
# data = insert_column(data, brand, brand.columns)
```

```{python}
new_sum = data[data['month'] < '2018-01'].groupby(['pid','size']).sum()['units']
```

```{python}
data = data.drop(['category'], axis=1)
data = data.drop(['mainCategory'], axis=1)
data = data.drop(['subCategory'], axis=1)
data = data.drop(['color'], axis=1)
data = data.drop(['brand'], axis=1)
#data = data.drop(['pid'], axis=1)
#data = data.drop(['size'], axis=1)
#data = data.drop(['releaseDate'], axis=1)
data = data.drop(['mcat-1'], axis=1)
```

### Criando variavel alvo

```{python}
from datetime import datetime
data['target'] = data['date'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d').day)
data = data.drop(['date'], axis=1)
```

### Criando variavel do numero de dia desde o lançamento

```{python}
new_test = data[data['month'] == '2018-01']
```

```{python}
from datetime import datetime

d2 = datetime.strptime('2018-01-01','%Y-%m-%d')
new_test['releaseDate'] = new_test['releaseDate'].apply(lambda x: (d2 -datetime.strptime(x,'%Y-%m-%d')).days)
new_test = new_test[new_test['releaseDate'] >= 0]
```

### Criando variavel do intervalo entre as vendas

```{python}
new_data = pd.merge( new_sum,new_test, on=['pid','size'])
```

```{python}
t = train.sort_values(by=['pid','size','date'])
```

```{python}
from copy import deepcopy
aux_realclass = deepcopy(t)
```

```{python}
t = t[t['month'] < '2018-01']
```

```{python}
t['date'] = pd.to_datetime(t['date'], format='%Y-%m-%d')
```

```{python}
aux_realclass['date'] = pd.to_datetime(aux_realclass['date'], format='%Y-%m-%d')
```

```{python}
t['diff'] = t.groupby(['pid','size'])['date'].diff().apply(lambda x: x.days)
```

```{python}
aux_realclass['diff'] = aux_realclass.groupby(['pid','size'])['date'].diff().apply(lambda x: x.days)
```

```{python}
releases = items[['pid', 'size', 'releaseDate']] 
```

```{python}
a = pd.merge(t, releases, on=['pid','size'])
```

```{python}
rc = pd.merge(aux_realclass, releases, on=['pid','size'])
```

```{python}
a['releaseDate'] = pd.to_datetime(a['releaseDate'], format='%Y-%m-%d')
```

```{python}
rc['releaseDate'] = pd.to_datetime(rc['releaseDate'], format='%Y-%m-%d')
```

```{python}
untilRelease = (a['date'] - a['releaseDate']).apply(lambda x: x.days)
```

```{python}
untilRelease_realclass = (rc['date'] - rc['releaseDate']).apply(lambda x: x.days)
```

```{python}
import math
for i in range(len(a)):
    if(not (math.isnan(a.iloc[i]['diff']))):
        untilRelease[i] = a.iloc[i]['diff']
```

```{python}
import math
for i in range(len(rc)):
    if(not (math.isnan(rc.iloc[i]['diff']))):
        untilRelease_realclass[i] = rc.iloc[i]['diff']
```

```{python}
variavel_doida_de_Djeysi = untilRelease * a['units']
```

```{python}
variavel_doida_de_Djeysi_realclass = untilRelease_realclass * rc['units']
```

```{python}
a = a.drop(['releaseDate'], axis=1)
a['diff'] = untilRelease
a['frequency'] = variavel_doida_de_Djeysi
```

```{python}
rc = rc.drop(['releaseDate'], axis=1)
rc['diff'] = untilRelease_realclass
rc['frequency'] = variavel_doida_de_Djeysi_realclass
```

### Criando variavel intervalo medio entre as vendas

```{python}
mean_between_solds = a.groupby(['pid','size'])['diff'].mean()
```

```{python}
mean_between_solds_realclass = rc.groupby(['pid','size'])['diff'].mean()
```

### Criando variavel frequencia de vendas

```{python}
frequency = a.groupby(['pid','size'])['frequency'].sum() / a.groupby(['pid','size'])['frequency'].count()
```

```{python}
frequency_realclass = rc.groupby(['pid','size'])['frequency'].sum() / rc.groupby(['pid','size'])['frequency'].count()
```

```{python}
frequency =  pd.merge(frequency , mean_between_solds, on=['pid','size'])
```

```{python}
frequency_realclass =  pd.merge(frequency_realclass , mean_between_solds_realclass, on=['pid','size'])
```

```{python}
new_data = pd.merge(frequency, new_data, on=['pid','size'])
```

```{python}
realclass = pd.merge(frequency_realclass, realclass, on=['pid','size'])
```

### Preparando dados para treino e teste

```{python}
realclass = realclass.drop(['pid'], axis=1)
realclass = realclass.drop(['size'], axis=1)
```

```{python}
#new_test.columns = ['rrp', 'month', 'mcat-9', 'mcat-15', 'stock', 'target']
new_data = new_data.drop(['month'], axis=1)
new_data = new_data.drop(['pid'], axis=1)
new_data = new_data.drop(['size'], axis=1)

```

```{python}
new_data.columns = ['frequency', 'diff', 'units', 'rrp', 'releaseDate', 'mcat-9',
       'mcat-15', 'stock', 'target']
```

```{python}
realclass = realclass[new_data.columns]
```

```{python}
new_data = new_data.drop(['releaseDate'], axis=1)
realclass = realclass.drop(['releaseDate'], axis=1)
```

```{python}
y_train = new_data.iloc[:,-1]
X_train = new_data.iloc[:,0:-1]
```

```{python}
y_test = realclass.iloc[:,-1]
X_test = realclass.iloc[:,0:-1]
```

### Realizando treinamento e avaliação em diferentes metodos de regressão

```{python}
from sklearn.ensemble import RandomForestRegressor

regr = RandomForestRegressor(max_depth=2)
regr.fit(X_train, y_train)
predictions = regr.predict(X_test)
```

```{python}
evaluation(predictions, y_test)
```
